# Generated by Django 5.2.5 on 2025-08-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_assessment", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sites",
            name="risk_assessment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="risk_assessment.riskassessment",
            ),
        ),
    ]
