# Generated by Django 5.2.5 on 2025-08-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_sites_risk_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sites",
            name="security_type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
